name: Update Image URLs to jsDelivr CDN

on:
  push:
    branches:
      - main

jobs:
  update-cdn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Replace Image URLs
        run: |
          # JavaScript 스크립트 파일을 작성합니다.
          echo 'const fs = require("fs");' > replace-urls.js
          echo 'const path = require("path");' >> replace-urls.js
          echo 'const directory = "_site";' >> replace-urls.js
          echo 'const jsDelivrCDN = "https://cdn.jsdelivr.net/gh/radic2682/radic2682.github.io";' >> replace-urls.js
          echo '' >> replace-urls.js
          echo 'const replaceUrls = (filePath) => {' >> replace-urls.js
          echo '  const data = fs.readFileSync(filePath, "utf8");' >> replace-urls.js
          echo '  const updatedData = data.replace(/\/assets\/\d+\/[0-9a-f-]+$/g, (match) => `${jsDelivrCDN}${match}`);' >> replace-urls.js
          echo '  fs.writeFileSync(filePath, updatedData, "utf8");' >> replace-urls.js
          echo '};' >> replace-urls.js
          echo '' >> replace-urls.js
          echo 'const walk = (dir) => {' >> replace-urls.js
          echo '  const files = fs.readdirSync(dir);' >> replace-urls.js
          echo '  files.forEach((file) => {' >> replace-urls.js
          echo '    const filePath = path.join(dir, file);' >> replace-urls.js
          echo '    const stat = fs.statSync(filePath);' >> replace-urls.js
          echo '    if (stat.isDirectory()) {' >> replace-urls.js
          echo '      walk(filePath);' >> replace-urls.js
          echo '    } else if (file.endsWith(".html")) {' >> replace-urls.js
          echo '      replaceUrls(filePath);' >> replace-urls.js
          echo '    }' >> replace-urls.js
          echo '  });' >> replace-urls.js
          echo '};' >> replace-urls.js
          echo '' >> replace-urls.js
          echo 'walk(directory);' >> replace-urls.js

          # 스크립트 실행
          node replace-urls.js

          # 변경된 파일을 Git에 추가하고 커밋합니다.
          git config --global user.email "ash8663@naver.com"
          git config --global user.name "An Sun Hong"

          git add _site/
          git commit -m "Update image URLs to jsDelivr CDN"
          git push




