name: Update Image URLs to jsDelivr CDN

on:
  push:
    branches:
      - main # 변경사항을 원하는 브랜치에 맞게 설정합니다.

jobs:
  update-cdn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Replace Image URLs
        run: |
          find _site/ -name "*.html" -exec sed -i 's|/images/|https://cdn.jsdelivr.net/gh/radic2682/radic2682.github.io/images/|g' {} +
          git add _site/
          git commit -m "Update image URLs to jsDelivr CDN"
          git push

          